

name: pgcore
channels:
  - gimli
  - conda-forge
dependencies:
  - affine=2.4.0=pyhd8ed1ab_1
  - aiohttp=3.9.5=py311ha68e1ae_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - aom=3.9.1=he0c23c2_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.7.22=h67aab5a_5
  - aws-c-cal=0.6.15=h750c3ff_0
  - aws-c-common=0.9.19=h2466b09_0
  - aws-c-compression=0.2.18=h750c3ff_6
  - aws-c-event-stream=0.4.2=hd0fc785_13
  - aws-c-http=0.8.2=he5605a3_2
  - aws-c-io=0.14.9=h22d870b_2
  - aws-c-mqtt=0.10.4=h9c13125_6
  - aws-c-s3=0.5.10=h5bc95ef_3
  - aws-c-sdkutils=0.1.16=h750c3ff_2
  - aws-checksums=0.1.18=h750c3ff_6
  - aws-crt-cpp=0.26.12=h819e545_0
  - aws-sdk-cpp=1.11.329=hab43c70_5
  - azure-core-cpp=1.11.1=h249a519_1
  - azure-identity-cpp=1.6.0=h91493d7_1
  - azure-storage-blobs-cpp=12.10.0=h91493d7_1
  - azure-storage-common-cpp=12.5.0=h91493d7_4
  - blosc=1.21.5=hbd69f2e_1
  - branca=0.7.2=pyhd8ed1ab_0
  - brotli=1.1.0=hcfcfb64_1
  - brotli-bin=1.1.0=hcfcfb64_1
  - brotli-python=1.1.0=py311h12c1d0e_1
  - bzip2=1.0.8=hcfcfb64_5
  - c-ares=1.28.1=hcfcfb64_0
  - ca-certificates=2025.1.31=h56e8100_0
  - cairo=1.18.0=h91e5215_1
  - cartopy=0.24.0=py311hcf9f919_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cfitsio=4.4.0=h9b0cee5_1
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=win_pyh7428d3b_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contextily=1.6.2=pyhd8ed1ab_1
  - contourpy=1.2.1=py311h005e61a_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.1=py311h12c1d0e_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - double-conversion=3.3.0=h63175ca_0
  - eigen=3.4.0=h91493d7_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h63175ca_0
  - ffmpeg=6.1.1=gpl_h52c3a39_114
  - fiona=1.9.6=py311hee68897_3
  - fmt=10.2.1=h181d51b_0
  - folium=0.17.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.0=py311he736701_0
  - freetype=2.12.1=hdaf720e_2
  - freexl=2.0.0=h8276f4a_0
  - frozenlist=1.4.1=py311ha68e1ae_0
  - gdal=3.9.0=py311h6622a2a_7
  - geographiclib=2.0=pyhd8ed1ab_0
  - geopandas=0.14.4=pyhd8ed1ab_0
  - geopandas-base=0.14.4=pyha770c72_0
  - geopy=2.4.1=pyhd8ed1ab_1
  - geos=3.12.1=h1537add_0
  - geotiff=1.7.3=hd7df778_1
  - gl2ps=1.4.2=had7236b_1
  - glew=2.1.0=h39d44d4_2
  - glib=2.80.2=h0df6a38_0
  - glib-tools=2.80.2=h2f9d560_0
  - graphite2=1.3.13=h63175ca_1003
  - gst-plugins-base=1.24.4=hb0a98b8_1
  - gstreamer=1.24.4=h5006eae_1
  - gsw=3.6.19=py311h0a17f05_1
  - harfbuzz=8.5.0=h81778c3_0
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.3=nompi_h2b43c12_105
  - icu=73.2=h63175ca_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - intel-openmp=2024.1.0=h57928b3_966
  - ipykernel=6.29.4=pyh4bbf305_0
  - ipython=8.25.0=pyh7428d3b_0
  - ipywidgets=8.1.3=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jsoncpp=1.9.5=h2d74725_1
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h1ea47a8_0
  - jupyterlab_widgets=3.0.11=pyhd8ed1ab_0
  - kealib=1.5.3=h6c43f9b_1
  - kiwisolver=1.4.5=py311h005e61a_1
  - krb5=1.21.2=heb0366b_0
  - lcms2=2.16=h67d730c_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20240116.2=cxx17_h63175ca_0
  - libaec=1.1.3=h63175ca_0
  - libarchive=3.7.4=haf234dc_0
  - libblas=3.9.0=22_win64_mkl
  - libboost-headers=1.85.0=h57928b3_1
  - libbrotlicommon=1.1.0=hcfcfb64_1
  - libbrotlidec=1.1.0=hcfcfb64_1
  - libbrotlienc=1.1.0=hcfcfb64_1
  - libcblas=3.9.0=22_win64_mkl
  - libclang13=18.1.8=default_ha5278ca_0
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.8.0=hd5e4a3a_0
  - libdeflate=1.20=hcfcfb64_0
  - libexpat=2.6.2=h63175ca_0
  - libffi=3.4.2=h8ffe710_5
  - libflang=5.0.0=h6538335_20180525
  - libgdal=3.9.0=hfcf005a_7
  - libglib=2.80.2=h0df6a38_0
  - libgoogle-cloud=2.25.0=h5e7cea3_0
  - libgoogle-cloud-storage=2.25.0=hce61461_0
  - libgrpc=1.62.2=h5273850_0
  - libhwloc=2.10.0=default_h8125262_1001
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_2
  - libintl-devel=0.22.5=h5728263_2
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - libkml=1.3.0=haf3e7a6_1018
  - liblapack=3.9.0=22_win64_mkl
  - liblapacke=3.9.0=22_win64_mkl
  - libnetcdf=4.9.2=nompi_h92078aa_114
  - libogg=1.3.5=h2466b09_0
  - libopenblas=0.3.27=pthreads_hc140b1d_0
  - libopus=1.3.1=h8ffe710_1
  - libpng=1.6.43=h19919ed_0
  - libpq=16.3=hab9416b_0
  - libprotobuf=4.25.3=h503648d_0
  - libre2-11=2023.09.01=hf8d8778_2
  - librttopo=1.1.0=h94c4f80_15
  - libsodium=1.0.18=h8d14728_1
  - libspatialindex=2.0.0=h5a68840_0
  - libspatialite=5.1.0=h1b797e6_7
  - libsqlite=3.46.0=h2466b09_0
  - libssh2=1.11.0=h7dfc565_0
  - libtheora=1.1.1=hc70643c_1006
  - libtiff=4.6.0=hddb2be6_3
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.4.0=hcfcfb64_0
  - libxcb=1.16=hcd874cb_0
  - libxml2=2.12.7=h283a6d9_1
  - libzip=1.10.1=h1d365fa_3
  - libzlib=1.3.1=h2466b09_1
  - llvm-meta=5.0.0=0
  - loguru=0.7.2=py311h1ea47a8_1
  - lz4-c=1.9.4=hcfcfb64_0
  - lzo=2.10=hcfcfb64_1001
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mapclassify=2.6.1=pyhd8ed1ab_0
  - markupsafe=2.1.5=py311ha68e1ae_0
  - matplotlib=3.8.4=py311h1ea47a8_2
  - matplotlib-base=3.8.4=py311h9b31f6e_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mercantile=1.2.1=pyhd8ed1ab_1
  - metis=5.1.0=h63175ca_1007
  - minizip=4.0.6=hb638d1e_0
  - mkl=2024.1.0=h66d3029_692
  - more-itertools=10.3.0=pyhd8ed1ab_0
  - msgpack-python=1.0.8=py311h3257749_0
  - msys2-conda-epoch=20160418=1
  - multidict=6.0.5=py311ha68e1ae_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.3=pyhd8ed1ab_1
  - nlohmann_json=3.11.3=h1537add_0
  - numpy=1.26.4=py311h0b4df5a_0
  - openblas=0.3.27=pthreads_h3721920_0
  - openh264=2.4.1=h63175ca_0
  - openjpeg=2.5.2=h3d672ee_0
  - openmp=5.0.0=vc14_1
  - openssl=3.5.0=ha4e3fda_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py311hcf9f919_1
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.43=h17e33f8_0
  - pgcore=1.5.0=py311_1
  - pickleshare=0.7.5=py_1003
  - pillow=10.3.0=py311h5592be9_1
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.4=h63175ca_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - pooch=1.8.2=pyhd8ed1ab_0
  - poppler=24.04.0=h747fd5a_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=16.3=h7f155c9_0
  - proj=9.4.1=hd9569ee_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=5.9.8=py311ha68e1ae_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pugixml=1.14=h63175ca_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pybert=2.4.3=py_0
  - pygimli=1.5.3=py_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyproj=3.6.1=py311h93f6e28_7
  - pyqt=5.15.9=py311h125bc19_5
  - pyqt5-sip=12.12.2=py311h12c1d0e_5
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - pytest=8.2.2=pyhd8ed1ab_0
  - python=3.11.9=h631f459_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytz=2024.1=pyhd8ed1ab_0
  - pyvista=0.44.1=pyhd8ed1ab_0
  - pywin32=306=py311h12c1d0e_2
  - pyzmq=26.0.3=py311h484c95c_0
  - qt-main=5.15.8=hcef0176_21
  - qt6-main=6.7.2=h527115d_2
  - rasterio=1.3.10=py311hb019220_4
  - re2=2023.09.01=hd3b24a8_2
  - requests=2.32.3=pyhd8ed1ab_0
  - rtree=1.2.0=py311h44d53c4_1
  - scikit-learn=1.5.0=py311hdcb8d17_1
  - scipy=1.13.1=py311hd4686c6_0
  - scooby=0.10.0=pyhd8ed1ab_0
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - setuptools=70.1.0=pyhd8ed1ab_0
  - shapely=2.0.4=py311hcd532c9_1
  - sip=6.7.12=py311h12c1d0e_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.0=hfb803bf_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - spdlog=1.13.0=h64d2f7d_0
  - sqlite=3.46.0=h2466b09_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.2=py311h0a17f05_0
  - suitesparse=5.4.0=h5d0cbe0_1
  - svt-av1=2.1.0=he0c23c2_0
  - tbb=2021.12.0=hc790b64_1
  - tbb-devel=2021.12.0=hb551fcf_1
  - tetgen=1.6.0=ha925a31_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tiledb=2.24.1=hd1ea2a0_0
  - tk=8.6.13=h5226925_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.4.1=py311he736701_0
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - trame=3.6.3=pyhd8ed1ab_0
  - trame-client=3.2.1=pyhd8ed1ab_0
  - trame-server=3.0.3=pyhd8ed1ab_0
  - trame-vtk=2.8.9=pyhd8ed1ab_0
  - trame-vuetify=2.6.2=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - ucrt=10.0.22621.0=h57928b3_0
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.2.2=pyhd8ed1ab_0
  - utfcpp=4.0.5=h57928b3_0
  - vc=14.3=h8a93ad2_20
  - vc14_runtime=14.40.33810=ha82c5b3_20
  - vs2015_runtime=14.40.33810=h3bf8584_20
  - vtk=9.3.1=qt_py311h31e1f40_202
  - vtk-base=9.3.1=qt_py311h09991dd_202
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - widgetsnbextension=4.0.11=pyhd8ed1ab_0
  - win32_setctime=1.1.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - wslink=2.1.1=pyhd8ed1ab_0
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xerces-c=3.2.5=h63175ca_0
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xyzservices=2024.6.0=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - yarl=1.9.4=py311ha68e1ae_0
  - zeromq=4.3.5=he1f189c_4
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_1
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - h5py==3.12.1
      - importlib-resources==6.5.2
      - kneed==0.8.5
      - reda==0.2.4
prefix: C:\Users\mealiy001\AppData\Local\anaconda3\envs\pgcore
